AWSTemplateFormatVersion: 2010-09-09

Parameters:
  HostedZoneId:
    Description: Description
    Type: String
    Default: Z03295403K1WWCVX1E07K
  domainName:
    Description: Description
    Type: String
    Default: qas.demo.inductiveautomation.com
  release:
    Description: Description
    Type: String
    Default: blue
  blueStackFeAlb:
    Description: Description
    Type: String
    Default: cloud-pubdmoblu-2024-08280810-FeAlbEndpoint  
  greenStackFeAlb:
    Description: Description
    Type: String
    Default: cloud-pubdmogrn-2024-08280810-FeAlbEndpoint

Conditions:
    conditionRelease: !Equals ["blue", !Ref "release"]

Resources:
  DNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Comment: Zone apex alias targeted to LoadBalancer.
      RecordSets:
      - Name: !Ref domainName
        Type: A
        AliasTarget:
          HostedZoneId: !Ref HostedZoneId
          DNSName: 
          - Fn::ImportValue: !If [conditionRelease, !Ref blueStackFeAlb, !Ref greenStackFeAlb]
              #Fn::Sub: "${NetworkStackName}-FeAlbEndpoint"
          
#Outputs:

