AWSTemplateFormatVersion: 2010-09-09

Parameters:
  hostedZoneId:
    Description: Description
    Type: String
    Default: Z03295403K1WWCVX1E07K
  domainName:
    Description: Description
    Type: String
    Default: qas.demo.inductiveautomation.com
  release:
    Description: Description
    Type: String
    Default: blue
  blueStackFeAlbZoneId:
    Description: Description
    Type: String
    Default: cloud-pubdmoblu-2024-08280810::FeAlbEndpointHostedZone
  blueStackFeAlbEndpoint:
    Description: Description
    Type: String
    Default: cloud-pubdmoblu-2024-08280810::FeAlbEndpoint
  greenStackFeAlbZoneId:
    Description: Description
    Type: String
    Default: cloud-pubdmoblu-2024-08280810-FeAlbEndpointHostedZone
  greenStackFeAlbEndpoint:
    Description: Description
    Type: String
    Default: cloud-pubdmoblu-2024-08280810-FeAlbEndpoint #cloud-pubdmoblu-2024-08280810-FeAlbEndpoint

#Conditions:
#  conditionRelease: 

Resources:
  DNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref hostedZoneId
      Comment: Zone apex alias
      RecordSets:
        - Name: !Ref domainName
          Type: A
          AliasTarget:
            HostedZoneId: #!ImportValue cloud-pubdmoblu-2024-08280810-FeAlbEndpointHostedZone
              Fn::ImportValue:
                !Ref blueStackFeAlbZoneId
            DNSName: #!ImportValue cloud-pubdmoblu-2024-08280810-FeAlbEndpoint
              Fn::ImportValue:
                !Ref blueStackFeAlbEndpoint

#Outputs:
